version: '3.8'
services:
  web:
    build: ./
    command: uvicorn assignment.asgi:application --reload --workers 3 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8005:8000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      
    depends_on:
      - web-db
  
  web-db:
    image: postgres:14-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    