# Generated by Django 4.2 on 2023-12-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bn_name', models.CharField(max_length=150)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField(blank=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='districts',
            index=models.Index(fields=['name', 'lat', 'lon'], name='tasks_distr_name_65bcd5_idx'),
        ),
    ]
