# Generated by Django 4.2 on 2023-12-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
        migrations.RenameIndex(
            model_name='district',
            new_name='tasks_distr_name_c340eb_idx',
            old_name='tasks_distr_name_65bcd5_idx',
        ),
    ]
